### ISSUE TITLE
SKU Generation

### ISSUE THREAD

**Issue by Husseinbeygi** [MishkaTeam/UniBazzar#10]

**Comment by SajjadDoosty** [comment]
سلام

**Comment by SajjadDoosty** [comment]
بنظرم اینکه انبارداری بدونه این محصول از چه دسته بندی ایه بدردش نمیخوره لازم نیس

**Comment by Husseinbeygi** [comment]
پس چیا لازمه؟
تو خودت گفتی که مال انبارداریه

**Comment by SajjadDoosty** [comment]
انباردار محصولو پرت میکنه تو انبار نیازی نیس بدونه چیه، کدشم میزنه ک ب موجودی انبار اضافه شه همین

**Comment by MohammadSadeghAb** [comment]
ببین ممکنه اره الان به دردش نخوره اما اومدیم و فردا روز لازم داشتیم 
اگه الان بی معنی جنریت کنیم اونموقع به مشکل میخوریم 
اما اگه اونموقع لازم بشه داریم دیگه 
اگرم هیچ وقت لازم نشد خب چه فرقی میکنه یک کد بی معنی باشه یا نه دسته بندیش تو کده مشخص باشه

**Comment by MohammadSadeghAb** [comment]
هر چند به نظرم لازمش میشه چون به هر حال انبار دار باید بدونه که از فلان دسته بندی مثلا تو اون استور چقد موجودی داره دیگه

**Comment by SajjadDoosty** [comment]
بنظرم "50 عدد کالا در دسته بندی لبنیات" بدرد انباردار نمیخوره

**Comment by MohammadSadeghAb** [comment]
توی sku بزاریم کوئریمون سریع تر نمیشه؟

**Comment by SajjadDoosty** [comment]
منطقی نیس اصلا کله منطقمونو بزاریم روی sku خب اصلا کارش یه چیزه دیگس

**Comment by MohammadSadeghAb** [comment]
اره ولی بدون معنی جنریت کنیم هیچ استفاده‌ی خاصی نداره اینجوری اگرم الان به درد نخوره شاید بعدا به درد خورد

**Comment by MohammadSadeghAb** [comment]
حالا نمیدونم باز هرچی اکی بشه فرق خاصی نداره

**Comment by MohammadSadeghAb** [comment]
خب واسه اینکه فرق نداره معنی دار باشه یا نه 
طبق چیزایی که خوندم من راجبش دیگه همیناس که مثلا کالاهای مشابه یا ببینه هر دسته بندی چقد فروش داره بعد واسه شارژ کالاها بتونه استفاده کنه و اینا 
باید ببینیم روند پروژه چجوری میخواد بره 
دیگه اگه قرار نیست استفاده بشه از این سری مزایاش که خب اره یک کد بی معنی جنریت کنیم

**Comment by SajjadDoosty** [comment]
چون من طبق دیجیکالا و باسلام دارم حرف میزنم هیچکدوم معنی دار جنریت نکرده بودن و بنظرم لازمم نیس

**Comment by SajjadDoosty** [comment]
دیگه جمع بندی و حرف اخر اقای بیگی بزنن @Husseinbeygi

**Comment by Husseinbeygi** [comment]
با همون ایده ای @SajjadDoosty توی گروه دادی ( اینجا هم بذار ) پیش برید،
درصورتی که احساس کردیم نیاز به تغییر داره اونو اصلاحش میکنیم

**Comment by SajjadDoosty** [comment]
### SKU Generation

**Template:**
[UBZ]-[_StoreCode_]-[_NowTimestamp_] 

**Example:**
UBZ-001-5732642340

**Comment by SajjadDoosty** [comment]
### Index Fragmentation Test 

**Table:**
![2](https://github.com/user-attachments/assets/2fa38fda-099f-4b70-bf1d-da64b5baba2a) 

**Index fragmentation test:**
![1](https://github.com/user-attachments/assets/4e154d0d-d4f6-469a-8a67-61bdf036364a)

SKU template changes to:
[UBZ]-[NowTimestamp(in milliseconds)]

Final length: 17

**Comment by SajjadDoosty** [comment]
### SKU Generation v1.7
SKU template changes to:
[UBZ]-[NowTimestamp(in milliseconds)]

Final length: 17

**Comment by Husseinbeygi** [comment]
عالیه @SajjadDoosty

**Comment by Husseinbeygi** [comment]
@SajjadDoosty 
نگا اون ایندکس لولش صفر هستش، این یعنی احتمالا باید اون ستون GUID باشه 
پس احتمالا اون یکی دیگه باشه که صفر درصد هستش
من اینجوری برداشت کردم

**Comment by SajjadDoosty** [comment]
@Husseinbeygi
اها بله درست میگین

**Comment by MohammadSadeghAb** [comment]
تصمیم نهایی این شد SKU بدون معنی جنریت بشه
